config/routes.rb
Rails.application.routes.draw do
  resources :reflections
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reflection.rb
class Reflection < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reflections_controller.rb
class ReflectionsController < ApplicationController
  before_action :set_reflection, only: %i[ show edit update destroy ]

  # GET /reflections or /reflections.json
  def index
    @reflections = Reflection.all
  end

  # GET /reflections/1 or /reflections/1.json
  def show
  end

  # GET /reflections/new
  def new
    @reflection = Reflection.new
  end

  # GET /reflections/1/edit
  def edit
  end

  # POST /reflections or /reflections.json
  def create
    @reflection = Reflection.new(reflection_params)

    respond_to do |format|
      if @reflection.save
        format.html { redirect_to reflection_url(@reflection), notice: "Reflection was successfully created." }
        format.json { render :show, status: :created, location: @reflection }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reflection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reflections/1 or /reflections/1.json
  def update
    respond_to do |format|
      if @reflection.update(reflection_params)
        format.html { redirect_to reflection_url(@reflection), notice: "Reflection was successfully updated." }
        format.json { render :show, status: :ok, location: @reflection }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reflection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reflections/1 or /reflections/1.json
  def destroy
    @reflection.destroy

    respond_to do |format|
      format.html { redirect_to reflections_url, notice: "Reflection was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reflection
      @reflection = Reflection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reflection_params
      params.require(:reflection).permit(:item, :cost, :expense_category, :emotion, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reflections_helper.rb
module ReflectionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RosebudDb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reflections/_form.html.erb
<%= form_with(model: reflection) do |form| %>
  <% if reflection.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reflection.errors.count, "error") %> prohibited this reflection from being saved:</h2>

      <ul>
        <% reflection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :item, style: "display: block" %>
    <%= form.text_field :item %>
  </div>

  <div>
    <%= form.label :cost, style: "display: block" %>
    <%= form.text_field :cost %>
  </div>

  <div>
    <%= form.label :expense_category, style: "display: block" %>
    <%= form.text_field :expense_category %>
  </div>

  <div>
    <%= form.label :emotion, style: "display: block" %>
    <%= form.text_field :emotion %>
  </div>

  <div>
    <%= form.label :comment, style: "display: block" %>
    <%= form.text_area :comment %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reflections/_reflection.html.erb
<div id="<%= dom_id reflection %>">
  <p>
    <strong>Item:</strong>
    <%= reflection.item %>
  </p>

  <p>
    <strong>Cost:</strong>
    <%= reflection.cost %>
  </p>

  <p>
    <strong>Expense category:</strong>
    <%= reflection.expense_category %>
  </p>

  <p>
    <strong>Emotion:</strong>
    <%= reflection.emotion %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= reflection.comment %>
  </p>

</div>

app/views/reflections/edit.html.erb
<h1>Editing reflection</h1>

<%= render "form", reflection: @reflection %>

<br>

<div>
  <%= link_to "Show this reflection", @reflection %> |
  <%= link_to "Back to reflections", reflections_path %>
</div>

app/views/reflections/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reflections</h1>

<div id="reflections">
  <% @reflections.each do |reflection| %>
    <%= render reflection %>
    <p>
      <%= link_to "Show this reflection", reflection %>
    </p>
  <% end %>
</div>

<%= link_to "New reflection", new_reflection_path %>

app/views/reflections/new.html.erb
<h1>New reflection</h1>

<%= render "form", reflection: @reflection %>

<br>

<div>
  <%= link_to "Back to reflections", reflections_path %>
</div>

app/views/reflections/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reflection %>

<div>
  <%= link_to "Edit this reflection", edit_reflection_path(@reflection) %> |
  <%= link_to "Back to reflections", reflections_path %>

  <%= button_to "Destroy this reflection", @reflection, method: :delete %>
</div>